<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RuntimeIdentifiers>android-arm64;ios-arm64;iossimulator-arm64;linux-arm64;linux-x64;osx;osx-arm64;osx-x64;win-arm64;win-x64</RuntimeIdentifiers>

    <!-- See setup-dotnet GitHub Actions workflow documentation -->
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder> 

    <PackageId>Diabase.ResultType</PackageId>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Authors>R-Technics</Authors>
    <RepositoryUrl>https://github.com/rtechnics/Diabase.ResultType</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
